# http://doc.gitlab.com/ce/ci/yaml/README.html
# https://gitlab.com/rychly-edu/docker/docker-openwrt-sdk

# Fixed OpenWrt version to rebuild on its version updates
image: prajval7433/docker-openwrt-sdk:22.03.1-ipq40xx

build:
  stage: build
  script:
    - export MAKEFLAGS="${MAKEFLAGS} OUTPUT_DIR=${CI_PROJECT_DIR}/bin -s"
    - /add-custom-local-feed.sh "${CI_PROJECT_DIR}"
    - /install-custom-feed-packages.sh
    - /reconfigure.sh
    - /make-custom-feed-packages.sh
    - /make-index.sh "${CI_PROJECT_DIR}/key-build"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - bin

pages:
  stage: deploy
  script:
    - mkdir -p "./public/${CI_COMMIT_REF_SLUG}"
    - /generate-repository.sh "${CI_PROJECT_DIR}/public/${CI_COMMIT_REF_SLUG}" "${CI_PROJECT_DIR}/key-build.pub" "${CI_PROJECT_DIR}/bin" "${CI_PROJECT_DIR}/47bc41ad54a6601d"
    - mv LICENSE "./public/${CI_COMMIT_REF_SLUG}"
    - ./generate-webpage.sh "${CI_PROJECT_DIR}/public/${CI_COMMIT_REF_SLUG}" > "./public/${CI_COMMIT_REF_SLUG}/index.html"
  artifacts:
    name: ${CI_COMMIT_REF_SLUG}
    paths:
      - public
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - bin