name: building sturdynet packages

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted
    container: sturdynetoci/docker-openwrt-sdk:22.03.1-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
#       - run: echo ${{ github.workspace }}
#       - run: echo $GITHUB_WORKSPACE
      - run: export MAKEFLAGS="${MAKEFLAGS} OUTPUT_DIR=${GITHUB_WORKSPACE}/bin -s"
#       - run: echo ${MAKEFLAGS}
#       - run: echo ${GITHUB_WORKSPACE}
      - run: cd flow_broker && ls && cd ..
      - run: /add-custom-local-feed.sh "${GITHUB_WORKSPACE}"
      - run: /install-custom-feed-packages.sh
      - run: /reconfigure.sh
      - run: /make-custom-feed-packages.sh
      - run: /make-index.sh "${GITHUB_WORKSPACE}/key-build"
      - run: mkdir -p "${GITHUB_WORKSPACE}/public/${GITHUB_HEAD_REF}"
      - run: /generate-repository.sh "${GITHUB_WORKSPACE}/public/${GITHUB_HEAD_REF}" "${GITHUB_WORKSPACE}/key-build.pub" "${GITHUB_WORKSPACE}/bin" "${GITHUB_WORKSPACE}/47bc41ad54a6601d"
      - run: mv LICENSE "${GITHUB_WORKSPACE}/public/${GITHUB_HEAD_REF}"
      - run: ./generate-webpage.sh "${GITHUB_WORKSPACE}/public/${GITHUB_HEAD_REF}" > "${GITHUB_WORKSPACE}/public/${GITHUB_HEAD_REF}/index.html"
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: ${GITHUB_HEAD_REF}
          path: public

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-openwrt-sdk:22.03.1-latest
