name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted
    container: sturdynetoci/docker-openwrt-sdk:22.03.1-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: ls && pwd
#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-openwrt-sdk:22.03.1-latest
